services:
  # ==========================================================================
  # Data - Data services (preprocessing)
  # ==========================================================================
  cleaning:
    build:
      context: .
      dockerfile: docker/data/cleaning/Dockerfile
    container_name: mlops-data-cleaning
    volumes:
      # Monter les volumes dans /app/data (pas /data !)
      - ./data/raw:/app/data/raw:ro           # :ro = read-only pour sécurité
    # Met le service sur un réseau dédié, permet de s'y connecter depuis d'autres containers
    networks:
      - mlops-network

  preprocessing:
    build:
      context: .
      dockerfile: docker/data/preprocessing/Dockerfile
    container_name: mlops-data-preprocessing
    volumes:
      # Monter les volumes dans /app/data (pas /data !)
      - ./data/processed:/app/data/processed      # read-write pour les outputs
      - ./models:/app/models:ro                   # read-only pour les models
    networks:
      - mlops-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


networks:
  mlops-network:
    driver: bridge
