services:
  # ==========================================================================
  # ETL - Data Cleaning
  # ==========================================================================
  cleaning:
    build:
      context: .
      dockerfile: docker/clean_data/Dockerfile
    container_name: mlops-clean_data

  volumes:
    - ./data/raw:/data/raw
    - ./data/cleaned:/data/cleaned
